FROM python:3.12-slim

WORKDIR /app

# Copy project files into container root
COPY . /app

RUN python -m pip install --upgrade pip

# Install dependencies needed for tests
RUN pip install pytest

RUN pip install -r requirements.

# Expose app directory to pythonpath
ENV PYTHONPATH=/app

ENTRYPOINT ["pytest", "src/tests/test_data_downloader.py"]