FROM python:3.12-slim

WORKDIR /app

RUN python -m pip install --upgrade pip

# Install dependencies needed for tests
RUN pip install pytest

# Copy project files into container root
COPY . /app

RUN pip install -r requirements.txt

# Expose app directory to pythonpath
ENV PYTHONPATH=/app

ENTRYPOINT ["pytest", "src/tests/base_data_loading_test.py"]